schedule:
  - day: 0
    start_time: "20:00"
    duration: "2 часа"
    place: "КС, зал"
    max_players: 15
  - day: 3
    start_time: "21:00"
    duration: "2 часа"
    place: "КС, зал"
    max_players: 15
